name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Run tests
        run: go test -v ./...
      
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      
  build:
    name: Build binaries
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: go-test-watcher-linux-amd64
          - os: macos-latest
            artifact_name: go-test-watcher-darwin-amd64
          - os: windows-latest
            artifact_name: go-test-watcher-windows-amd64.exe
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Build binary
        run: |
          VERSION=$(git describe --tags --always --dirty)
          go build -ldflags="-X 'main.Version=${VERSION}'" -o ${{ matrix.artifact_name }}
      
      - name: Upload asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./${{ matrix.artifact_name }} 